// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPageWeather;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_ValueTemperature;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_ValueFeelsLike;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_ValueSunrise;
lv_obj_t * ui_Label5;
lv_obj_t * ui_ValueSunset;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_ValueHumidity;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Pressure;
lv_obj_t * ui_ValuePressure;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_ValueWindSpeed;
lv_obj_t * ui_ValueWindDirection;
lv_obj_t * ui_Image1;
lv_obj_t * ui_ValueDate;
lv_obj_t * ui_ValueTime;
lv_obj_t * ui_ValueLastUpdate;
lv_obj_t * ui_TabPageSettings;
lv_obj_t * ui_DayLight;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
